default_context:
    name: "{{ cookiecutter.author_name }}"
    email: "{{ cookiecutter.author_email }}"
    github_username: "{{ cookiecutter.hosting_github_username_or_org }}"
    project_name: "{{ cookiecutter.project_name }}"
    project_slug: "{{ cookiecutter.project_slug }}"
    python_slug: "{{ cookiecutter.python_slug }}"
    project_short_description: "{{ cookiecutter.project_short_description }}"
    pypi_username: "{{ cookiecutter.pypi_username }}"
    version: "{{ cookiecutter.version }}"
    license: "{{ cookiecutter.license }}"